export const roomLayout = [
{
  type: "tile",
  imgNumberInString: "06",
  imgClass: "wall",
  clickable: false,
  positionX: 0,
  positionY: 0,
},
{
  type: "tile",
  imgNumberInString: "06",
  imgClass: "wall",
  clickable: false,
  positionX: 1,
  positionY: 0,
},
{
  type: "tile",
  imgNumberInString: "06",
  imgClass: "wall",
  clickable: false,
  positionX: 2,
  positionY: 0,
},
{
  type: "tile",
  imgNumberInString: "07",
  imgClass: "wall",
  clickable: false,
  positionX: 3,
  positionY: 0,
},
{
  type: "tile",
  imgNumberInString: "06",
  imgClass: "wall",
  clickable: false,
  positionX: 4,
  positionY: 0,
},

{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 0,
  positionY: 1,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 1,
  positionY: 1,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 2,
  positionY: 1,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 3,
  positionY: 1,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 4,
  positionY: 1,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 0,
  positionY: 2,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 1,
  positionY: 2,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 2,
  positionY: 2,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 3,
  positionY: 2,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 4,
  positionY: 2,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 0,
  positionY: 3,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 1,
  positionY: 3,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 2,
  positionY: 3,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 3,
  positionY: 3,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 4,
  positionY: 3,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 0,
  positionY: 4,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 1,
  positionY: 4,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 2,
  positionY: 4,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 3,
  positionY: 4,
},
{
  type: "tile",
  imgNumberInString: "02",
  imgClass: "floor",
  clickable: false,
  positionX: 4,
  positionY: 4,
},

{
  type: "prop",
  imgNumberInString: "02",
  imgClass: "guitar",
  clickable: true,
  positionX: 3.3,
  positionY: 1.3,
  width: 14,
  height: 32,
  modal: "hobbies",
  href: undefined,
  floatText: "Hobbies",
  floatHeight: 50,
},
{
  type: "prop",
  imgNumberInString: "02",
  imgClass: "book-shelf",
  clickable: true,
  positionX: 0.5,
  positionY: 0.1,
  width: 28,
  height: 32,
  modal: "aboutMe",
  href: undefined,
  floatText: "About Me",
  floatHeight: 0,
},
{
  type: "prop",
  imgNumberInString: "02",
  imgClass: "table",
  clickable: false,
  positionX: 0,
  positionY: 3,
  width: 64,
  height: 32,
  modal: "test",
  href: undefined,
},
{
  type: "prop",
  imgNumberInString: "02",
  imgClass: "computer",
  clickable: true,
  positionX: 2,
  positionY: 2.5,
  width: 17,
  height: 27,
  modal: "educationWork",
  href: undefined,
  floatText: "Education and Work",
  floatHeight: 50,
},
{
  type: "prop",
  imgNumberInString: "02",
  imgClass: "envelope",
  clickable: true,
  positionX: 3.5,
  positionY: 3.5,
  width: 20,
  height: 11,
  modal: "test",
  href: "https://hikaru-inoue-portfolio.jimdosite.com/contact/",
  floatText: "Contact",
  floatHeight: 50,
},
];
